import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useTheme } from 'next-themes'
import HeroSection from '@/components/HeroSection'
import ServicesFeatures from '@/components/ServicesFeatures'
import NewsletterSection from '@/components/NewsletterSection'
import NextCards from '@/components/NextCards'
import ServicesSection from '@/components/ServicesSection'

export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <main className={styles.main}>
        <HeroSection />
        <ServicesFeatures />
        <NextCards />
        <ServicesSection />
        <NewsletterSection />
      </main>
    </>
  )
}
